# Generated by Django 4.1.2 on 2022-10-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
